Genre.destroy_all

tv_show =           Genre.create!( name: 'TV Show')
movie =             Genre.create!( name: 'Movie')
rom_com =           Genre.create!( name: 'Rom-com')
comedy =            Genre.create!( name: 'Comedy')
romance =           Genre.create!( name: 'Romance' )
adventureous =      Genre.create!( name: 'Action & Adventure')
suspense =          Genre.create!( name: 'Suspense' )
mystery =           Genre.create!( name: 'Mystery' )
slice_of_life =     Genre.create!( name: 'Slice of Life')
sitcoms =           Genre.create!( name: 'Sitcomes' )
coming_of_age =     Genre.create!( name: 'Coming of age' )
chinese_language =  Genre.create!( name: 'Chinese-languaged')
real_life =         Genre.create!( name: 'Based on events in real life')
narrative =         Genre.create!( name: 'Narrative')
documentaries =     Genre.create!( name: 'Documentaries')
docuseries =        Genre.create!( name: 'Docuseries')
webseries =         Genre.create!( name: 'Webseries')
happy =             Genre.create!( name: 'Happy')
dark =              Genre.create!( name: 'Dark')
witty =             Genre.create!( name: 'Witty' )
quirky =            Genre.create!( name: 'Quirky' )
drama =             Genre.create!( name: 'Dramas' )
heartfelt =         Genre.create!( name: 'Heartfelt')
fantasy =           Genre.create!( name: 'Fantasy')
emotional =         Genre.create!( name: 'Emotional')
chilling =          Genre.create!( name: 'Chilling')
inspiring =         Genre.create!( name: 'Inspiring')
recently_added =    Genre.create!( name: 'Recently Added')
award_wining =      Genre.create!( name: 'Award Winner')

