Genre.destroy_all

tv_show =           Genre.create!( name: 'tv show')
movie =             Genre.create!( name: 'movie')
rom_com =           Genre.create!( name: 'rom-com')
dark =              Genre.create!( name: 'dark-toned')
happy =             Genre.create!( name: 'happy-toned')
adventureous =      Genre.create!( name: 'action & adventure')
comedy =            Genre.create!( name: 'comedy')
narrative =         Genre.create!( name: 'narrative')
slice_of_life =     Genre.create!( name: 'slice of life')
webseries =         Genre.create!( name: 'webseries')
chinese_language =  Genre.create!( name: 'chinese-languaged')
suspense =          Genre.create!( name: 'suspense' )
mystery =           Genre.create!( name: 'mystery' )
coming_of_age =     Genre.create!( name: 'coming of age' )
romance =           Genre.create!( name: 'romance' )
sitcoms =           Genre.create!( name: 'sitcomes' )
witty =             Genre.create!( name: 'witty' )
quirky =            Genre.create!( name: 'quirky' )
drama =             Genre.create!( name: 'dramas' )
heartfelt =         Genre.create!( name: 'heartfelt')
documentaries =     Genre.create!( name: 'documentaries')
real_life =         Genre.create!( name: 'Based on events in real life')
fantasy =           Genre.create!( name: 'fantasy')
emotional =         Genre.create!( name: 'emotional')
chilling =          Genre.create!( name: 'chilling')
docuseries =        Genre.create!( name: 'docuseries')
inspiring =         Genre.create!( name: 'inspiring')
recently_added =    Genre.create!( name: 'recently_added')


